#!/bin/bash

sed -i .bak 's/Clockwork Orange,/Clockwork Orange/g' annotations_database.txt
sed -i .bak 's/400 Blows,/400 Blows/g' annotations_database.txt
sed -i .bak 's/Godfather Part II,/Godfather Part II/g' annotations_database.txt
sed -i .bak 's/Timespamp, Username, Sample_name, Class/Timespamp,Username,Sample_name,Class/g' annotations_database.txt
sed -i .bak 's#N/A#None#g' annotations_database.txt
